name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn opencv-python PyQt5 requests

      - name: Run the application
        run: |
          nohup uvicorn Facial_recognition:app --host 127.0.0.1 --port 8000
